---
title: "Project2"
author: "JL"
date: "11/15/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(jsonlite)
library(tidyverse)
library(tidytext)
library(topicmodels)
library(SnowballC)
library(randomForest)
library(stringi)
library(gridExtra)
library(tidytext)
library(ggthemes)
library(tm)
library(reshape2)
```

```{r cars}
automotive <- jsonlite::stream_in(file("Project Data/reviews_Automotive_5.json"))%>% 
  mutate(name="automotive")

amazon_instant <- jsonlite::stream_in(file("Project Data/reviews_Amazon_Instant_Video_5.json"))%>% 
  mutate(name="amazon_instant")

apps_for_android <- jsonlite::stream_in(file("Project Data/reviews_Apps_for_Android_5.json"))

baby <- jsonlite::stream_in(file("Project Data/reviews_Baby_5.json"))

beauty <- jsonlite::stream_in(file("Project Data/reviews_Beauty_5.json"))

#books <- jsonlite::stream_in(file("Project Data/reviews_Books_5.json"))

cds_vinyl <- jsonlite::stream_in(file("Project Data/reviews_CDs_and_Vinyl_5.json"))

cell_phones_and_accessories<- jsonlite::stream_in(file("Project Data/reviews_Cell_Phones_and_Accessories_5.json"))

clothing_shoes <- jsonlite::stream_in(file("Project Data/reviews_Clothing_Shoes_and_Jewelry_5.json"))

digital_music <- jsonlite::stream_in(file("Project Data/reviews_Digital_Music_5.json"))

electronics <- jsonlite::stream_in(file("Project Data/reviews_Electronics_5.json"))

grocery <- jsonlite::stream_in(file("Project Data/reviews_Grocery_and_Gourmet_Food_5.json"))

health_and_personal <- jsonlite::stream_in(file("Project Data/reviews_Health_and_Personal_Care_5.json"))

home_kitchen <- jsonlite::stream_in(file("Project Data/reviews_Home_and_Kitchen_5.json"))

kindle_store <- jsonlite::stream_in(file("Project Data/reviews_Kindle_Store_5.json"))

movies_and_tv <- jsonlite::stream_in(file("Project Data/reviews_Movies_and_TV_5.json"))

musical <- jsonlite::stream_in(file("Project Data/reviews_Musical_Instruments_5.json")) %>% 
  mutate(name="musical")

office_products <- jsonlite::stream_in(file("Project Data/reviews_Office_Products_5.json"))

patio_lawn <- jsonlite::stream_in(file("Project Data/reviews_Patio_Lawn_and_Garden_5.json"))

pet <- jsonlite::stream_in(file("Project Data/reviews_Pet_Supplies_5.json"))

sports_outdoors <- jsonlite::stream_in(file("Project Data/reviews_Sports_and_Outdoors_5.json"))

tools <- jsonlite::stream_in(file("Project Data/reviews_Tools_and_Home_Improvement_5.json"))

toys_games <- jsonlite::stream_in(file("Project Data/reviews_Toys_and_Games_5.json"))

video_games<- jsonlite::stream_in(file("Project Data/reviews_Video_Games_5.json"))

#df<-rbind(amazon_instant,apps_for_android, automotive, baby, cds_vinyl, cell_phones_and_accessories, clothing_shoes, digital_music, electronics, grocery, health_and_personal, home_kitchen, kindle_store, movies_and_tv, musical, office_products, patio_lawn, pet, sports_outdoors, tools, toys_games, video_games)

df<-rbind(amazon_instant,automotive,musical)
```

```{r}
deduped <- df[!duplicated(df$reviewText), ]
deduped$reviewTime <- as.POSIXct(deduped$reviewTime, format = "%m %d, %Y", tz = "EST")
deduped$reviewText<- as.character(deduped$reviewText)
deduped$id <- 1:nrow(deduped)
deduped$reviewTime <- as.POSIXct(deduped$reviewTime)
```

```{r}
df<-select(deduped,reviewerID,asin, reviewText, overall, summary, reviewTime,helpful,name)
```


```{r}
#data(stop_words)
deduped %>%
  unnest_tokens(word, reviewText) %>%
  anti_join(stop_words) %>%
  mutate(word = wordStem(word)) %>%
  count(word, sort = T) %>%
  filter(n>3000) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) + 
  geom_col() +
  xlab(NULL) +
  coord_flip()
```

```{r}

temp <- deduped %>%
  unnest_tokens(word, reviewText) %>%
  anti_join(stop_words) %>%
  mutate(word = wordStem(word)) %>%
  count(word, sort = T)

final <- deduped %>%
  unnest_tokens(word, reviewText) %>%
  anti_join(stop_words) %>%
  mutate(word = wordStem(word)) %>%
  left_join(temp, on = "word") %>%
  bind_tf_idf(word, id, n)

final %>%
  arrange(desc(tf_idf)) %>%
  mutate(word = factor(word, levels = rev(unique(word))))%>% 
  top_n(20) %>%
  ggplot(aes(word, tf_idf)) +
  geom_col() +
  labs(x = NULL, y = "tf-idf") +
  coord_flip()


```

```{r}
mat_final <- final %>%
  cast_dtm(id, word, n)

ap_lda <- LDA(mat_final, k = 2, control = list(seed = 1234))
ap_lda
str(ap_lda)
ap_topics <- tidy(ap_lda, matrix = "beta")

ap_top_terms <- ap_topics %>%
  group_by(topic) %>%
  top_n(10, beta) %>%
  ungroup() %>%
  arrange(topic, -beta)

ap_top_terms %>%
  mutate(term = reorder(term, beta)) %>%
  ggplot(aes(term, beta, fill = factor(topic))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topic, scales = "free") +
  coord_flip()

beta_spread <- ap_topics %>%
  mutate(topic = paste0("topic", topic)) %>%
  spread(topic, beta) %>%
  filter(topic1 > .001 | topic2 > .001) %>%
  mutate(log_ratio = log2(topic2 / topic1))

beta_spread
```

```{r}
##plot_austen %>% 
# group_by(book) %>% 
#  top_n(15) %>% 
#  ungroup %>%
#  ggplot(aes(word, tf_idf, fill = book)) +
#  geom_col(show.legend = FALSE) +
#  labs(x = NULL, y = "tf-idf") +
#  facet_wrap(~book, ncol = 2, scales = "free") +
#  coord_flip()
```


```{r}
df2<- df %>% 
  mutate(reviewLength=stri_length(reviewText)) %>% 
  rename(Rating=overall)
 
test <- df2 %>% 
  select(helpful) %>% 
  unlist()

df2<-df2 %>% 
  mutate(helpful=test[c(T,F)],not_helpful=test[c(F,T)]-test[c(T,F)],perc_helpful=ifelse(helpful==0,0,helpful/(helpful+not_helpful)))
```



Distrubution and Visualization of the Variables

```{r}
#Basic Variables to Break Down:
#Helpful, Rating, reviewLengthFactor

#Helpful
ggplot(df2,aes(x=Rating,y=perc_helpful,group=Rating,fill=Rating))+geom_boxplot()+scale_y_continuous(limits = c(.001,1.00001))+guides(fill=FALSE)+ylab("% Reviews Helpful") #removing perc_helpful==-0 values as they are most likely the 0,0 helpful/not_helpful ones

#Rating
ggplot(df2,aes(x=Rating))+geom_bar(stat="count",aes(fill=as.factor(Rating)))+geom_text(stat='bin',aes(label=..count..),vjust=-1,binwidth=1)+ggtitle("Ratings Distribution")+theme(legend.position="none")
#ReviewLengthFactor
ggplot(df2,aes(x=reviewLength))+geom_bar(stat="count")+scale_x_continuous(limits = c(0,1000))+theme_classic()#Values more than 1000 continued the trend

#Extra Stuff
#Prolific User vs avgRating
prolific_users<-df2 %>% 
  group_by(reviewerID) %>% 
  summarise(reviews=n(),meanRating=mean(Rating),meanLength=mean(reviewLength),popularity=sum(helpful)-sum(not_helpful))

ggplot(prolific_users,aes(x=reviews,meanRating))+geom_point()+stat_smooth()+scale_x_continuous(limits = c(5,50)) 
#as reviews increase, scores tend to go down

#Prolific User vs Helpful
next_plot_data<-prolific_users %>% 
  filter(popularity>-25 & popularity<50, reviews<20 & reviews>4)

ggplot(next_plot_data,aes(x=popularity,y=reviews,fill=meanRating)) + geom_raster(hjust=0,vjust=0)

ggplot(next_plot_data,aes(x=reviews,y=popularity,fill=meanRating))+geom_raster(interpolate = F)

ggplot(filter(prolific_users,popularity<500 & popularity > -200),
  aes(x=popularity,y=meanRating,color=meanLength)) + 
  geom_point() + 
  stat_smooth()
```


```{r}
#Distribution of Rating itself
hist(df2$Rating)
```


```{r}
#Review Length and Rating
ggplot(df2,aes(x=reviewLength))+geom_density()

df2<-sample_n(df2, 10000)

df2<-df2 %>% 
  filter(reviewLength<6000) %>% 
  mutate(reviewLengthFactor=ifelse(reviewLength<200,"Short",ifelse(reviewLength<600,"Medium","Long")))

All<-ggplot(df2,aes(x=reviewLength,y=Rating))+geom_point()+geom_jitter()+stat_smooth(method="gam")+ggtitle("ReviewLength vs Rating (out of 5) for all reviews")

Short<-ggplot(filter(df2,reviewLengthFactor=="Short"),aes(x=reviewLength,y=Rating))+geom_point()+geom_jitter()+stat_smooth(method="lm")+ggtitle("ReviewLength vs Rating (out of 5) for short reviews")

Medium<-ggplot(filter(df2,reviewLengthFactor=="Medium"),aes(x=reviewLength,y=Rating))+geom_point()+geom_jitter()+stat_smooth(method="lm")+ggtitle("ReviewLength vs Rating (out of 5) for medium length reviews")

Long<-ggplot(filter(df2,reviewLengthFactor=="Long"),aes(x=reviewLength,y=Rating))+geom_point()+geom_jitter()+stat_smooth(method="lm")+ggtitle("ReviewLength vs Rating (out of 5) for long reviews")

grid.arrange(All, Short, Medium, Long, ncol=2)
cor(df2$Rating,df2$reviewLength)
```

```{r}
#Review Helpfulness and Rating
ggplot(df2,aes(x=helpful))+geom_bar()+scale_x_continuous(limits = c(-1, 25)) #maxed out at 25 to give a sense of scale

ggplot(df2,aes(x=helpful,y=Rating,color=Rating))+geom_point()+stat_smooth()+geom_jitter()+scale_x_continuous(limits=c(-1,25))+theme(legend.position="none")
cor(df2$helpful,df2$Rating)
```

```{r}
counts<-df2 %>%
  group_by(asin) %>% 
  summarise(reviewCount=n(),productAVG=mean(Rating)) %>% 
  filter(reviewCount<75)

ggplot(counts,aes(x=reviewCount,y=productAVG))+geom_point()+stat_smooth()
cor(counts$reviewCount,counts$productAVG)
```

```{r}
individuals<-df2 %>%
  group_by(reviewerID) %>% 
  summarise(numReviews=n(),AvgRating=mean(Rating))

ggplot(individuals,aes(x=numReviews,y=AvgRating))+geom_point()+stat_smooth()
cor(counts$reviewCount,counts$productAVG)
```

Deliverables
•	Correlation of words with Score
•	Distribution & Visualization of basic variables
o	Score
•	Text Analysis
o	nGram analysis?
o	Corelation with words and score
•	Model – not including Text – with text
•	Get actual product data



```{r}
grouped_data<-df2 %>%  #data grouped by product and given num_reviews and num_score
  group_by(asin) %>% 
  summarise(meanScore=mean(Rating),nReviews=n()) %>% 
  mutate(meanScore=round(meanScore,1))

ggplot(grouped_data,aes(x=meanScore))+geom_bar(stat="count")+theme_economist()

```

